package com.example.moviesnews
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val recyclerView: RecyclerView = findViewById(R.id.recyclerView)
        val adapter = ArticlesAdapter(this, getArticles())
        recyclerView.adapter = adapter
        recyclerView.layoutManager = LinearLayoutManager(this)

        }

        fun getArticles(): List<Article> {
            return listOf(
                Article("Every Movie In The Batman Universe, Now Including Joker: Folie à Deux, Ranked [Update]", "Where does Todd Phillips' sequel to Joker fit in the Caped Crusader's cinematic canon?", R.drawable.img1, "By Ashley Bardhan", "Published October 4, 2024", "Some call Batman the “Caped Crusader,” while others call him Christian Bale, Kevin Conroy, Michael Keaton…In his 85-year-long tenure as a sulky billionaire with wings, Batman has found the time to be a generous movie star, so today we honor him by ranking notable movies set in the Batman universe. (Apologies, Adam West fans, but 1966's Batman: The Movie isn’t here. We won’t complain if it remains #1 in your own personal ranking, though.) As you read through this list, you’ll notice that some Batman movies have a huge quality gap. For example, it’s tough to pit the controversial 2017 Justice League—which was ultimately outshone by Zack Snyder’s four-hour director’s cut—against Christopher Nolan’s highly regarded The Dark Knight Trilogy. In other cases, Batman has nipples on his suit, but I tried not to let that influence my rankings."),
                Article("Dune: Part Two Delayed To 2024 Due To Actors’ And Writers’ Strikes", "The highly anticipated sci-fi sequel has been pushed back.", R.drawable.img2, "By Mary Kate Carr", "Published October 4, 2024", "Dune: Part Two, Denis Villeneuve’s follow-up to his Oscar-winning 2021 adaptation of Frank Herbert’s sci-fi epic, has been delayed to March 15, 2024, Warner Bros. announced today. The film was originally slated to hit theaters on November 3. The delay comes as a result of the ongoing actors’ and writers’ strikes, which have brought Hollywood to a standstill."),
                Article("Taylor Swift Announces The Eras Tour Concert Film", "Coming to theaters on October 13.", R.drawable.img3, "By Mary Kate Carr", "Published October 4, 2024", "Swifties, rejoice! After months of speculation, Taylor Swift has officially announced that a concert film of her record-breaking Eras Tour will be coming to theaters in North America on October 13. The film, directed by Sam Wrench, promises to capture the magic of Swift’s three-hour-plus setlist, which spans her entire musical career."),
                Article("Netflix’s ‘Pain Hustlers’ Shows How Opioid Addiction Is A Business", "Emily Blunt and Chris Evans star in this based-on-a-true story drama.", R.drawable.img4, "By Saloni Gajjar", "Published October 4, 2024", "In the new Netflix film Pain Hustlers, Emily Blunt plays Liza Drake, a single mother who gets a job at a pharmaceutical start-up. She’s quickly seduced by the money and the lifestyle that comes with it, but soon realizes that the company is pushing a highly addictive opioid."),
                Article("The Best Horror Movies Of 2024 (So Far)", "From demonic nuns to killer dolls, this year has already delivered some scares.", R.drawable.img5, "By Angelica Jade Bastién", "Published October 4, 2024", "2024 has been a surprisingly strong year for horror movies, with a diverse range of films that have terrified and thrilled audiences. From the demonic chills of The Nun II to the unsettling social commentary of M3GAN, there’s something for every horror fan to enjoy."),
                Article("5 New Netflix Shows And Movies To Watch This Weekend", "Including a spooky anthology series and a heartwarming rom-com.", R.drawable.img6, "By Olivia Truffaut-Wong", "Published October 4, 2024", "Looking for something new to watch this weekend? Netflix has got you covered with a fresh batch of movies and TV shows. Whether you’re in the mood for spooky scares, heartwarming romance, or thought-provoking drama, there’s something for everyone on offer."),
                Article("‘Loki’ Season 2: Everything We Know So Far", "The God of Mischief is back for more time-traveling adventures.", R.drawable.img7, "By Sam Barsanti", "Published October 4, 2024", "Loki, the Marvel Cinematic Universe’s trickster god, is back for a second season of time-traveling shenanigans. After the mind-bending events of season 1, Loki finds himself in a new timeline, facing new threats and new allies."),
                Article("‘Saw X’ Review: A Bloody Good Time For Jigsaw Fans", "The latest installment in the horror franchise is a gruesome and satisfying return to form.", R.drawable.img8, "By Katie Rife", "Published October 4, 2024", "Saw X, the tenth installment in the long-running horror franchise, sees the return of Tobin Bell as John Kramer, aka Jigsaw. This time, Jigsaw is back with a new game, targeting a group of medical professionals who have wronged him in the past."),
                Article("‘The Exorcist: Believer’ Review: A Decent Sequel That Doesn’t Quite Possess The Original’s Power", "The legacy sequel to the 1973 classic delivers some scares, but lacks the original’s impact.", R.drawable.img9, "By A.A. Dowd", "Published October 4, 2024", "The Exorcist: Believer, the latest attempt to revive the iconic horror franchise, picks up decades after the events of the original film. Two young girls are possessed by a demonic force, and their families turn to a familiar face for help: Chris MacNeil, the mother from the original film."),
                Article("The Best Sci-Fi Movies Of 2024 (So Far)", "From space operas to dystopian thrillers, this year has been a great one for sci-fi fans.", R.drawable.img1, "By Scott Tobias", "Published October 4, 2024", "2024 has been a banner year for science fiction cinema, with a wide range of films exploring the possibilities of the future and the limits of human imagination. From the epic scope of Dune: Part Two to the intimate character study of After Yang, there’s something for every sci-fi fan to enjoy."),
                Article("Replicating Article Data for RecyclerView", "Creating a list of 20 articles with dummy data.", R.drawable.img1, "By Bard", "Published October 5, 2024", "This example demonstrates how to create a list of Article objects with dummy data for use in a RecyclerView. Each article has a title, subtitle, image resource, author, publish date, and content."),
                Article("Building a Simple RecyclerView Adapter", "Implementing a basic RecyclerView adapter in Kotlin.", R.drawable.img2, "By Bard", "Published October 5, 2024", "This code snippet shows how to create a simple RecyclerView adapter in Kotlin. It covers the essential methods like onCreateViewHolder, onBindViewHolder, and getItemCount."),
                Article("Handling Click Events in RecyclerView", "Adding click listeners to RecyclerView items.", R.drawable.img3, "By Bard", "Published October 5, 2024", "This example demonstrates how to handle click events on items in a RecyclerView. It uses an interface to communicate the click event to the activity or fragment."),
                Article("Using DiffUtil for Efficient RecyclerView Updates", "Optimizing RecyclerView updates with DiffUtil.", R.drawable.img4, "By Bard", "Published October 5, 2024", "This code snippet shows how to use DiffUtil to efficiently update a RecyclerView when the data changes. DiffUtil calculates the differences between the old and new data and only updates the necessary items."),
                Article("Adding Item Decorations to RecyclerView", "Customizing the appearance of RecyclerView items with item decorations.", R.drawable.img5, "By Bard", "Published October 5, 2024", "This example demonstrates how to add item decorations to a RecyclerView to customize the appearance of items. It covers adding dividers, spacing, and other visual elements."),
                Article("Implementing Swipe-to-Dismiss in RecyclerView", "Adding swipe-to-dismiss functionality to RecyclerView items.", R.drawable.img6, "By Bard", "Published October 5, 2024", "This code snippet shows how to implement swipe-to-dismiss functionality in a RecyclerView. It uses ItemTouchHelper to handle the swipe gestures and remove items from the adapter."),
                Article("Creating Custom Item Animations in RecyclerView", "Adding custom animations to RecyclerView items.", R.drawable.img7, "By Bard", "Published October 5","Some call Batman the “Caped Crusader,” while others call him Christian Bale, Kevin Conroy, Michael Keaton…In his 85-year-long tenure as a sulky billionaire with wings, Batman has found the time to be a generous movie star, so today we honor him by ranking notable movies set in the Batman universe. (Apologies, Adam West fans, but 1966's Batman: The Movie isn’t here. We won’t complain if it remains #1 in your own personal ranking, though.) As you read through this list, you’ll notice that some Batman movies have a huge quality gap. For example, it’s tough to pit the controversial 2017 Justice League—which was ultimately outshone by Zack Snyder’s four-hour director’s cut—against Christopher Nolan’s highly regarded The Dark Knight Trilogy. In other cases, Batman has nipples on his suit, but I tried not to let that influence my rankings." ),
            )


}
}
